### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by jcwatson11** [smarcet/JOSE4PHP#2]
On your README.md, the install instructions don't actually install your package.

To install a composer package, you need to run:

composer require [package name]

The instructions you pasted are for installing composer itself, and even at that, they are not complete.

Apart from that, even when I do try to install your package correctly using composer, it doesn't work, because it can't find the right version of phpseclib, because the tag you're asking for in your composer.json file doesn't exist in the phpseclib tag set.

**Comment by smarcet** [comment]
weird its was working fine on production ... however i updated the version tag to a recent one

https://github.com/phpseclib/phpseclib/releases/tag/1.0.0
regards
